name: Generate contribution snake

on:
  schedule:
    - cron: "0 18 * * *"   # runs daily at 18:00 UTC
  workflow_dispatch:       # manual run button

permissions:
  contents: write          # allow pushing to the repo

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: kabhilan27
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
